name: $(Version).$(rev:r)

trigger:
  branches:
    include:
    - release/*

pr: none

stages:
- stage: BuildPublish
  displayName: 'Release: Build and Publish'

  jobs:
  - job: BuildTestPublish
    displayName: 'Release: Build, Test and Publish on Windows'

    pool:
      vmImage: 'windows-latest'

    workspace:
      clean: all

    steps:
    - template: 'builds/template-steps-build-test.yaml'
      parameters:
        configuration: 'Release'
    - template: 'builds/template-steps-publish.yaml'
      parameters:
        configuration: 'Release'

# - stage: Release
#   displayName: 'Release: To NuGet'

#   jobs:
#   - template: 'template-job-release.yaml'